title: VeequeJay Portfolio
email: joviunique@gmail.com
description: >
  A dope portfolio for a passionate and skilled creator.
baseurl: "" 
url: "https://veequejay.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
